### PR TITLE
[RELEASE-v1.10] add maistra annotation to generated gateways to disable IOR

### PR DESCRIPTION
**Pull request by ReToCode**
## Changes
- add maistra annotation to generated gateways to disable IOR generation of OCP Routes

JIRA: https://issues.redhat.com/browse/SRVKS-1099

/assign @nak3 @skonto 

I'll also cherry-pick this to 1.9 and main.

### CODE REVIEW

**Comment by nak3** [comment]
Umm...It seems `Test / test / Unit Tests (pull_request)` on 1.10 is failing do you want to fix it?

**Comment by ReToCode** [comment]
Seems networking is really broken at RH side :D 

>   repository registry.access.redhat.com/ubi9/python-39 not found: name unknown: Repo not found

**Comment by nak3** [comment]
/lgtm
/approve

Yeah, let's skip `Security / analyze / Check Unicode CC (pull_request) ` one as it passed yesterday... https://github.com/openshift-knative/net-istio/actions/runs/5611775314

**Comment by ReToCode** [comment]
/override "Security / analyze / Check Unicode CC"

**Pull request merged**
